http:
  host: 'localhost'
  port: 3000

db:
  remote:
    use: 'mysql'
    ip: '120.79.183.77'
    port: 3306
    database: 'tututufdb'
    root: 'root'
    psw: '123456'

  sqlite:
    database: 'sqlite.db'